# Generated by Django 2.2 on 2019-05-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Promotion',
        ),
    ]
